version: "3.9"

services:
  backend:
    build: ./backend
    container_name: satellite-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./satellite-image-ui
    container_name: satellite-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
